---
title: "Vehicle Emissions - Combination of Inputs"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
    social: menu

runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library(flexdashboard)
library(tidyverse)
library(plotly)
library(knitr)
library(DT)
library(lubridate)
df <- read_csv('finaldata2.csv')


make_input <- unique(df$make)
transmission_input <- unique(df$transmission)
```

{.sidebar}
=======================================================================

Select the desired range of emissions per mile to filter vehicles that pollute that amount. 

Select desired make

Select transmission type: 0 for automatic and 1 for manual


```{r}
sliderInput(inputId = "emissions_input",
            label = h3("Emissions Range"),
            min = min(df$emissions_per_mile, na.rm=TRUE),
            max = max(df$emissions_per_mile, na.rm=TRUE),
            value= c(200, 500))

selectInput(inputId = "make_input", 
            label = h3("make"),
            choices = make_input, 
            selected = 'HONDA')

checkboxGroupInput(inputId = "fuel_input", 
                   label = h3("Fuel Type"),
                   choices = unique(df$fuel), 
                   inline = TRUE,
                   selected = '0')
```

Main Tab 1
=======================================================================

Column {data-width=500}
-----------------------------------------------------------------------

### Scatter Plot - City MPG & Emissions

```{r}
renderPlotly({
  p1 <- df %>% 
    filter(emissions_per_mile>input$emissions_input[1], emissions_per_mile<input$emissions_input[2]) %>% 
    filter(make %in% input$make_input) %>% 
    filter(fuel== input$fuel_input) %>% 
    ggplot(aes(x=city_mpg, y=emissions_per_mile))+
    geom_point()
  ggplotly(p1)
})
```

Column {data-width=500}
-----------------------------------------------------------------------

### Scatter Plot - Highway MPG & Emissions

```{r}
renderPlotly({
  p2 <- df %>% 
    filter(emissions_per_mile>input$emissions_input[1], emissions_per_mile<input$emissions_input[2]) %>% 
    filter(fuel==input$fuel_input) %>% 
    filter(make %in% input$make_input) %>%  
    ggplot(aes(x=highway_mpg, y=emissions_per_mile))+
    geom_point()
  ggplotly(p2)
})
```